"""initial schema

Revision ID: ae778706176e
Revises: 
Create Date: 2026-03-05 21:49:38.838938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae778706176e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disposals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('coin', sa.String(length=20), nullable=False),
    sa.Column('sell_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sell_amount', sa.Numeric(precision=28, scale=18), nullable=False),
    sa.Column('proceeds_sek', sa.Numeric(precision=28, scale=18), nullable=False),
    sa.Column('cost_basis_sek', sa.Numeric(precision=28, scale=18), nullable=False),
    sa.Column('gain_loss_sek', sa.Numeric(precision=28, scale=18), nullable=False),
    sa.Column('gav_at_disposal', sa.Numeric(precision=28, scale=18), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_disposals_coin_timestamp', 'disposals', ['coin', 'sell_timestamp'], unique=False)
    op.create_index('ix_disposals_tax_year', 'disposals', ['tax_year'], unique=False)
    op.create_table('gav_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coin', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('amount_change', sa.Numeric(precision=28, scale=18), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=28, scale=18), nullable=False),
    sa.Column('total_cost_sek', sa.Numeric(precision=28, scale=18), nullable=False),
    sa.Column('gav_per_unit_sek', sa.Numeric(precision=28, scale=18), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gav_ledger_coin_timestamp', 'gav_ledger', ['coin', 'timestamp'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coin_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price_sek', sa.Numeric(precision=28, scale=18), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coin_id', 'date', name='uq_price_cache_coin_date')
    )
    op.create_index('ix_price_cache_coin_id_date', 'price_cache', ['coin_id', 'date'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('chain', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=True),
    sa.Column('is_mine', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wallets_address_chain', 'wallets', ['address', 'chain'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('source_platform', sa.String(length=50), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('base_coin', sa.String(length=20), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=28, scale=18), nullable=False),
    sa.Column('quote_coin', sa.String(length=20), nullable=True),
    sa.Column('quote_amount', sa.Numeric(precision=28, scale=18), nullable=True),
    sa.Column('fee_coin', sa.String(length=20), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=28, scale=18), nullable=True),
    sa.Column('tx_hash', sa.String(length=256), nullable=True),
    sa.Column('from_address', sa.String(length=256), nullable=True),
    sa.Column('to_address', sa.String(length=256), nullable=True),
    sa.Column('price_sek', sa.Numeric(precision=28, scale=18), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_base_coin_timestamp', 'transactions', ['base_coin', 'timestamp_utc'], unique=False)
    op.create_index('ix_transactions_timestamp_utc', 'transactions', ['timestamp_utc'], unique=False)
    op.create_index('ix_transactions_tx_hash', 'transactions', ['tx_hash'], unique=False)
    op.create_table('transfer_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tx_out_id', sa.Integer(), nullable=False),
    sa.Column('tx_in_id', sa.Integer(), nullable=False),
    sa.Column('match_method', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['tx_in_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['tx_out_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_links')
    op.drop_index('ix_transactions_tx_hash', table_name='transactions')
    op.drop_index('ix_transactions_timestamp_utc', table_name='transactions')
    op.drop_index('ix_transactions_base_coin_timestamp', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_wallets_address_chain', table_name='wallets')
    op.drop_table('wallets')
    op.drop_index('ix_price_cache_coin_id_date', table_name='price_cache')
    op.drop_table('price_cache')
    op.drop_table('import_batches')
    op.drop_index('ix_gav_ledger_coin_timestamp', table_name='gav_ledger')
    op.drop_table('gav_ledger')
    op.drop_index('ix_disposals_tax_year', table_name='disposals')
    op.drop_index('ix_disposals_coin_timestamp', table_name='disposals')
    op.drop_table('disposals')
    # ### end Alembic commands ###
